//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SHOWROOMMANAGER.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class employee
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public employee()
        {
            this.orders = new HashSet<order>();
        }
    
        public int employee_id { get; set; }
        public string employee_name { get; set; }
        public Nullable<System.DateTime> employee_birthday { get; set; }
        public Nullable<decimal> employee_salary { get; set; }
        public string employee_phone { get; set; }
        public string employee_email { get; set; }
        public Nullable<int> showroom_id { get; set; }
    
        public virtual Showroom Showroom { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<order> orders { get; set; }
    }
}
