//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SHOWROOMMANAGER.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class order
    {
        public int order_id { get; set; }
        public string order_name { get; set; }
        public string order_description { get; set; }
        public Nullable<System.DateTime> order_time { get; set; }
        public int product_id { get; set; }
        public int customer_id { get; set; }
        public int employee_id { get; set; }
    
        public virtual customer customer { get; set; }
        public virtual employee employee { get; set; }
        public virtual product product { get; set; }
    }
}
